name: Deploy

on:
  push:
    branches:
      - build-system

jobs:
  deploy:
    name: Deploy CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ./build.sh

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        #if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: build-system-out
          folder: dist
