name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Deploy CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ./build.sh

      - name: Deploy (GitHub Pages)
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist

      - name: Deploy (S3)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --content-encoding utf-8 --delete
        env:
          AWS_S3_BUCKET: ${{ AWS_S3_BUCKET }}
          AWS_REGION: ${{ AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: dist
          DEST_DIR: theme/en/sigma

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CF_DISTRIBUTION }}
          PATHS: /theme/en/sigma
          AWS_REGION: ${{ AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
