on:
  push:
    paths:
      - '*.css'

name: Stylelint

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/stylelint@master
