name: Stylelint

on:
  push:
    paths:
      - '*.css'

jobs:
  lint:
    name: Check CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Stylelint
        uses: actions-hub/stylelint@master
